import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='bg-yellow-700'>
          <section className='container mx-auto bg-green-600'>header</section>
        </header>
        <main className='min-h-screen bg-gradient-to-tl bg-red-200'>
          {children}
        </main>
        <footer className='bg-gray-800'>
          <section className='container mx-auto bg-green-600'>
            <p className='bg-gray-500 text-center'>
              &copy; AllRights resrved by GMDfolio.2025
            </p>
          </section>
        </footer>
      </body>
    </html>
  );
}
